#ifndef ONECONTROLFACTROY_GLOBAL_H
#define ONECONTROLFACTROY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ONECONTROLFACTROY_LIBRARY)
#  define ONECONTROLFACTROYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ONECONTROLFACTROYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ONECONTROLFACTROY_GLOBAL_H
