#ifndef CONTROLFACTORY_GLOBAL_H
#define CONTROLFACTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTROLFACTORY_LIBRARY)
#  define CONTROLFACTORYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTROLFACTORYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTROLFACTORY_GLOBAL_H
